services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: challengeuser
      POSTGRES_PASSWORD: challengepass
      POSTGRES_DB: challengemanager
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challengeuser -d challengemanager"]
      interval: 2s
      timeout: 3s
      retries: 30

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: