"""init

Revision ID: a114a3534821
Revises:
Create Date: 2026-08-20 02:20:28.159342

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a114a3534821"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modifier_user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_Users_id"), "Users", ["id"], unique=False)
    op.create_table(
        "Challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("rules", sa.String(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "FITNESS",
                "NUTRITION",
                "MENTAL_HEALTH",
                "PRODUCTIVITY",
                "SOCIAL_RESPONSIBILITY",
                "OTHER",
                name="challengecategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "challenge_type",
            sa.Enum("RecurringChallenge", "OneTimeChallenge", name="challengetype"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modifier_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "recurrence_pattern",
            sa.Enum("Daily", "Weekly", "Monthly", "yearly", name="recurringtype"),
            nullable=False,
        ),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Challenges_id"), "Challenges", ["id"], unique=False)
    op.create_table(
        "Enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "enrolled", "pending", "in_progress", "done", name="enrollmentstatus"
            ),
            nullable=False,
        ),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["Challenges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["Users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "challenge_id", name="uq_user_challenge"),
    )
    op.create_index(op.f("ix_Enrollments_id"), "Enrollments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Enrollments_id"), table_name="Enrollments")
    op.drop_table("Enrollments")
    op.drop_index(op.f("ix_Challenges_id"), table_name="Challenges")
    op.drop_table("Challenges")
    op.drop_index(op.f("ix_Users_id"), table_name="Users")
    op.drop_table("Users")
    # ### end Alembic commands ###
