"""catch up schema to models

Everything the models grew while every environment ran on SQLite (where
`bootstrap_db.sync_sqlite_schema` added it instead of a migration): OTP,
comments, reactions, push, groups, roadmaps, notifications, roles and the
challenge image/identity/group columns.

Revision ID: bfb2303d362b
Revises: a7c31d8be402
Create Date: 2026-09-13 19:33:56.171636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb2303d362b'
down_revision: Union[str, Sequence[str], None] = 'a7c31d8be402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OtpCodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OtpCodes_id'), 'OtpCodes', ['id'], unique=False)
    op.create_index(op.f('ix_OtpCodes_mobile'), 'OtpCodes', ['mobile'], unique=False)
    op.create_index('ix_otpcodes_ip_created', 'OtpCodes', ['request_ip', 'created_at'], unique=False)
    op.create_index('ix_otpcodes_mobile_created', 'OtpCodes', ['mobile', 'created_at'], unique=False)
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sticker', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comments_id'), 'Comments', ['id'], unique=False)
    op.create_index(op.f('ix_Comments_user_id'), 'Comments', ['user_id'], unique=False)
    op.create_index('ix_comments_subject', 'Comments', ['subject_type', 'subject_id', 'parent_id', 'created_at'], unique=False)
    op.create_table('Groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('emblem', sa.String(length=60), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Groups_id'), 'Groups', ['id'], unique=False)
    op.create_index(op.f('ix_Groups_parent_id'), 'Groups', ['parent_id'], unique=False)
    op.create_table('PushSubscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=128), nullable=False),
    sa.Column('auth', sa.String(length=48), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_PushSubscriptions_id'), 'PushSubscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_PushSubscriptions_user_id'), 'PushSubscriptions', ['user_id'], unique=False)
    op.create_index('ix_pushsubscriptions_user', 'PushSubscriptions', ['user_id'], unique=False)
    op.create_table('Reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject_type', 'subject_id', 'kind', name='uq_reaction_once')
    )
    op.create_index(op.f('ix_Reactions_id'), 'Reactions', ['id'], unique=False)
    op.create_index(op.f('ix_Reactions_user_id'), 'Reactions', ['user_id'], unique=False)
    op.create_index('ix_reactions_subject', 'Reactions', ['subject_type', 'subject_id', 'kind'], unique=False)
    op.create_table('GroupInvites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=43), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GroupInvites_code'), 'GroupInvites', ['code'], unique=True)
    op.create_index(op.f('ix_GroupInvites_id'), 'GroupInvites', ['id'], unique=False)
    op.create_index('ix_group_invites_group', 'GroupInvites', ['group_id'], unique=False)
    op.create_table('GroupJoinRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GroupJoinRequests_id'), 'GroupJoinRequests', ['id'], unique=False)
    op.create_index('ix_group_requests_group_status', 'GroupJoinRequests', ['group_id', 'status'], unique=False)
    op.create_index('ix_group_requests_user', 'GroupJoinRequests', ['user_id'], unique=False)
    op.create_table('GroupMemberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_GroupMemberships_id'), 'GroupMemberships', ['id'], unique=False)
    op.create_index('ix_group_memberships_group', 'GroupMemberships', ['group_id'], unique=False)
    op.create_index('ix_group_memberships_user', 'GroupMemberships', ['user_id'], unique=False)
    op.create_table('Roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image_square', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('lifecycle_status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('strict', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('count_prior_progress', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roadmaps_group_id'), 'Roadmaps', ['group_id'], unique=False)
    op.create_index(op.f('ix_Roadmaps_id'), 'Roadmaps', ['id'], unique=False)
    op.create_index('ix_roadmaps_owner', 'Roadmaps', ['owner_id'], unique=False)
    op.create_table('Notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenges.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Notifications_id'), 'Notifications', ['id'], unique=False)
    op.create_index(op.f('ix_Notifications_user_id'), 'Notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_created', 'Notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('RoadmapEnrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'roadmap_id', name='uq_user_roadmap')
    )
    op.create_index(op.f('ix_RoadmapEnrollments_id'), 'RoadmapEnrollments', ['id'], unique=False)
    op.create_index('ix_roadmap_enrollments_roadmap', 'RoadmapEnrollments', ['roadmap_id'], unique=False)
    op.create_index('ix_roadmap_enrollments_user', 'RoadmapEnrollments', ['user_id'], unique=False)
    op.create_table('RoadmapInvites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=43), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RoadmapInvites_code'), 'RoadmapInvites', ['code'], unique=True)
    op.create_index(op.f('ix_RoadmapInvites_id'), 'RoadmapInvites', ['id'], unique=False)
    op.create_index('ix_roadmap_invites_roadmap', 'RoadmapInvites', ['roadmap_id'], unique=False)
    op.create_table('RoadmapSteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('stage_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('order_in_stage', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('completion_rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenges.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['Roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'challenge_id', name='uq_roadmap_challenge')
    )
    op.create_index(op.f('ix_RoadmapSteps_id'), 'RoadmapSteps', ['id'], unique=False)
    op.create_index('ix_roadmap_steps_challenge', 'RoadmapSteps', ['challenge_id'], unique=False)
    op.create_index('ix_roadmap_steps_roadmap', 'RoadmapSteps', ['roadmap_id'], unique=False)
    op.create_table('RoadmapStepProgress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='locked', nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modifier_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_enrollment_id'], ['RoadmapEnrollments.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['RoadmapSteps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_enrollment_id', 'step_id', name='uq_roadmap_progress')
    )
    op.create_index(op.f('ix_RoadmapStepProgress_id'), 'RoadmapStepProgress', ['id'], unique=False)
    op.create_index('ix_roadmap_progress_state', 'RoadmapStepProgress', ['roadmap_enrollment_id', 'state'], unique=False)
    op.add_column('Challenges', sa.Column('image_square', sa.String(length=40), nullable=True))
    op.add_column('Challenges', sa.Column('image_tall', sa.String(length=40), nullable=True))
    op.add_column('Challenges', sa.Column('identity_mode', sa.String(length=16), server_default='named', nullable=False))
    op.add_column('Challenges', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('Challenges', sa.Column('group_audience', sa.String(length=16), server_default='selected', nullable=False))
    op.add_column('Challenges', sa.Column('participation_mode', sa.String(length=16), server_default='optional', nullable=False))
    op.create_index(op.f('ix_Challenges_group_id'), 'Challenges', ['group_id'], unique=False)
    op.create_foreign_key(None, 'Challenges', 'Groups', ['group_id'], ['id'])
    op.add_column('Enrollments', sa.Column('role', sa.String(length=16), server_default='participant', nullable=False))
    op.add_column('Enrollments', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('Users', sa.Column('mobile', sa.String(length=16), nullable=True))
    op.add_column('Users', sa.Column('mobile_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Users', sa.Column('role', sa.String(length=16), server_default='member', nullable=False))
    op.add_column('Users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('Users', sa.Column('country', sa.String(length=60), nullable=True))
    op.add_column('Users', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('Users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('Users', sa.Column('muted_notification_kinds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_Users_mobile'), 'Users', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_mobile'), table_name='Users')
    op.drop_column('Users', 'muted_notification_kinds')
    op.drop_column('Users', 'address')
    op.drop_column('Users', 'city')
    op.drop_column('Users', 'country')
    op.drop_column('Users', 'phone')
    op.drop_column('Users', 'role')
    op.drop_column('Users', 'mobile_verified_at')
    op.drop_column('Users', 'mobile')
    op.drop_column('Enrollments', 'is_anonymous')
    op.drop_column('Enrollments', 'role')
    op.drop_constraint(None, 'Challenges', type_='foreignkey')
    op.drop_index(op.f('ix_Challenges_group_id'), table_name='Challenges')
    op.drop_column('Challenges', 'participation_mode')
    op.drop_column('Challenges', 'group_audience')
    op.drop_column('Challenges', 'group_id')
    op.drop_column('Challenges', 'identity_mode')
    op.drop_column('Challenges', 'image_tall')
    op.drop_column('Challenges', 'image_square')
    op.drop_index('ix_roadmap_progress_state', table_name='RoadmapStepProgress')
    op.drop_index(op.f('ix_RoadmapStepProgress_id'), table_name='RoadmapStepProgress')
    op.drop_table('RoadmapStepProgress')
    op.drop_index('ix_roadmap_steps_roadmap', table_name='RoadmapSteps')
    op.drop_index('ix_roadmap_steps_challenge', table_name='RoadmapSteps')
    op.drop_index(op.f('ix_RoadmapSteps_id'), table_name='RoadmapSteps')
    op.drop_table('RoadmapSteps')
    op.drop_index('ix_roadmap_invites_roadmap', table_name='RoadmapInvites')
    op.drop_index(op.f('ix_RoadmapInvites_id'), table_name='RoadmapInvites')
    op.drop_index(op.f('ix_RoadmapInvites_code'), table_name='RoadmapInvites')
    op.drop_table('RoadmapInvites')
    op.drop_index('ix_roadmap_enrollments_user', table_name='RoadmapEnrollments')
    op.drop_index('ix_roadmap_enrollments_roadmap', table_name='RoadmapEnrollments')
    op.drop_index(op.f('ix_RoadmapEnrollments_id'), table_name='RoadmapEnrollments')
    op.drop_table('RoadmapEnrollments')
    op.drop_index('ix_notifications_user_created', table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_user_id'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_id'), table_name='Notifications')
    op.drop_table('Notifications')
    op.drop_index('ix_roadmaps_owner', table_name='Roadmaps')
    op.drop_index(op.f('ix_Roadmaps_id'), table_name='Roadmaps')
    op.drop_index(op.f('ix_Roadmaps_group_id'), table_name='Roadmaps')
    op.drop_table('Roadmaps')
    op.drop_index('ix_group_memberships_user', table_name='GroupMemberships')
    op.drop_index('ix_group_memberships_group', table_name='GroupMemberships')
    op.drop_index(op.f('ix_GroupMemberships_id'), table_name='GroupMemberships')
    op.drop_table('GroupMemberships')
    op.drop_index('ix_group_requests_user', table_name='GroupJoinRequests')
    op.drop_index('ix_group_requests_group_status', table_name='GroupJoinRequests')
    op.drop_index(op.f('ix_GroupJoinRequests_id'), table_name='GroupJoinRequests')
    op.drop_table('GroupJoinRequests')
    op.drop_index('ix_group_invites_group', table_name='GroupInvites')
    op.drop_index(op.f('ix_GroupInvites_id'), table_name='GroupInvites')
    op.drop_index(op.f('ix_GroupInvites_code'), table_name='GroupInvites')
    op.drop_table('GroupInvites')
    op.drop_index('ix_reactions_subject', table_name='Reactions')
    op.drop_index(op.f('ix_Reactions_user_id'), table_name='Reactions')
    op.drop_index(op.f('ix_Reactions_id'), table_name='Reactions')
    op.drop_table('Reactions')
    op.drop_index('ix_pushsubscriptions_user', table_name='PushSubscriptions')
    op.drop_index(op.f('ix_PushSubscriptions_user_id'), table_name='PushSubscriptions')
    op.drop_index(op.f('ix_PushSubscriptions_id'), table_name='PushSubscriptions')
    op.drop_table('PushSubscriptions')
    op.drop_index(op.f('ix_Groups_parent_id'), table_name='Groups')
    op.drop_index(op.f('ix_Groups_id'), table_name='Groups')
    op.drop_table('Groups')
    op.drop_index('ix_comments_subject', table_name='Comments')
    op.drop_index(op.f('ix_Comments_user_id'), table_name='Comments')
    op.drop_index(op.f('ix_Comments_id'), table_name='Comments')
    op.drop_table('Comments')
    op.drop_index('ix_otpcodes_mobile_created', table_name='OtpCodes')
    op.drop_index('ix_otpcodes_ip_created', table_name='OtpCodes')
    op.drop_index(op.f('ix_OtpCodes_mobile'), table_name='OtpCodes')
    op.drop_index(op.f('ix_OtpCodes_id'), table_name='OtpCodes')
    op.drop_table('OtpCodes')
    # ### end Alembic commands ###
