/* Writes the one value the fallback page needs out of app.config.json.
 *
 * The page below the shell is local and static -- it has to be, since it is
 * what renders when the server cannot be reached -- so it cannot ask anything
 * for the address to retry. Rather than typing that address a second time in
 * a second file (two places for one fact is one place to forget), it is
 * generated here and `npm run sync` runs this first.
 *
 * The output is committed like the icons and the emoji catalogue are: it is
 * generated artwork, not a build artifact, and the app must work with no
 * toolchain present. */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(await readFile(join(root, "app.config.json"), "utf8"));

const out = join(root, "www", "server-url.js");
await writeFile(
  out,
  `/* Generated by scripts/apply-config.mjs from app.config.json. Do not edit. */\n` +
    `window.__SERVER_URL__ = ${JSON.stringify(cfg.serverUrl)};\n`,
  "utf8"
);

console.log(`wrote www/server-url.js  ->  ${cfg.serverUrl}`);
